language: node_js
node_js:
  - 0.8
before_script: node_modules/browserify/bin/cmd.js --entry client/src/lib/main.js -o public/client.js
notifications:
  webhooks: 
    urls:
      - http://webhooks.nodejitsu.com/1/deploy
    on_success: always
    on_failure: never
